name: EpicKillstreaks
author: [LimeGlass, Songoda]
description: Add Killstreaks to Minecraft.
version: @version@
main: com.songoda.killstreaks.Killstreaks
commands:
  killstreaks:
    description: Killstreaks main command.
    aliases: [epickillstreaks, ek, killstreak]
    usage: /killstreaks
permissions:
  epickillstreaks.*:
    description: Gives access to all Killstreaks commands.
    children:
      epickillstreaks.other: true
      epickillstreaks.check: true
  epickillstreaks.check:
    description: Gives access for a player to check their own killstreaks.
    default: op
  epickillstreaks.other:
    description: Gives access to check other player's killstreaks.
    default: op